# Generated by Django 3.2.8 on 2021-12-03 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('novedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='aprendizNovedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.aprendiz'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='tipoNovedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.tiponovedad'),
        ),
        migrations.AddField(
            model_name='historicaltiponovedad',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnovedad',
            name='aprendizNovedad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.aprendiz'),
        ),
        migrations.AddField(
            model_name='historicalnovedad',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnovedad',
            name='tipoNovedad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='novedades.tiponovedad'),
        ),
        migrations.AddField(
            model_name='historicalinasistencia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
