# Generated by Django 3.2.8 on 2021-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='acta',
            field=models.FileField(blank=True, upload_to='static'),
        ),
    ]
