# Generated by Django 3.2.8 on 2021-12-03 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('tipoDocumentoUsuario', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('NCS', 'Número ciego SENA'), ('PS', 'Pasaporte'), ('DNI', 'Documento Nacional de Identificación'), ('NIT', 'Número de Identificación Tributaria'), ('PR', 'PEP - RAMV'), ('PEP', 'PEP')], default='CC', max_length=3)),
                ('numeroDocumentoUsuario', models.IntegerField(unique=True)),
                ('nombresUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidosUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('rolUsuario', models.CharField(choices=[('IN', 'Instructor'), ('AP', 'Aprendiz'), ('AA', 'Apoyo administrativo'), ('CO', 'Coordinador'), ('AD', 'Administrador')], max_length=2)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='perfil/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAsignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAsignatura', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('idCentro', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCentro', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
            },
        ),
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('idCoordinacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCoordinacion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Coordinacion',
                'verbose_name_plural': 'Coordinaciones',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('nombreCentro', models.CharField(blank=True, max_length=255, null=True)),
                ('nombreCoordinacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombrePrograma', models.CharField(blank=True, max_length=255, null=True)),
                ('versionPrograma', models.CharField(blank=True, max_length=255, null=True)),
                ('idFicha', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFicha', models.IntegerField(unique=True)),
                ('anio', models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Año')),
                ('trimestre', models.IntegerField()),
                ('cantidadAprendices', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('correoAlterno', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.centro')),
                ('coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coordinacion')),
            ],
            options={
                'verbose_name': 'Coordinador',
                'verbose_name_plural': 'Coordinadores',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('tipoDocumentoUsuario', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('NCS', 'Número ciego SENA'), ('PS', 'Pasaporte'), ('DNI', 'Documento Nacional de Identificación'), ('NIT', 'Número de Identificación Tributaria'), ('PR', 'PEP - RAMV'), ('PEP', 'PEP')], default='CC', max_length=3)),
                ('numeroDocumentoUsuario', models.IntegerField(db_index=True)),
                ('nombresUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidosUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('rolUsuario', models.CharField(choices=[('IN', 'Instructor'), ('AP', 'Aprendiz'), ('AA', 'Apoyo administrativo'), ('CO', 'Coordinador'), ('AD', 'Administrador')], max_length=2)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('image', models.TextField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('rolInstructor', models.CharField(choices=[('LF', 'Instructor lider de ficha'), ('LP', 'Instructor lider apoyo administrativo'), ('LA', 'Instructor lider de asignatura')], default='LA', max_length=2)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.asignatura')),
                ('coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coordinacion')),
                ('jefeInmediato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coordinador')),
                ('numeroFichaLider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ficha')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('telefonoAprendiz', models.BigIntegerField()),
                ('estadoAprendiz', models.CharField(max_length=200)),
                ('fichaAprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ficha')),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='ApoyoAdministrativo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coordinacion')),
            ],
            options={
                'verbose_name': 'Apoyo admnistrativo',
                'verbose_name_plural': 'Apoyos administrativos',
            },
            bases=('users.user',),
        ),
    ]
